### ISSUE TITLE
can you plz opensource the actionscript part?

### ISSUE THREAD

**Issue by ionull** [mojombo/clippy#13]
can't customize the ui now~~thanks!

**Comment by mojombo** [comment]
The source is in `clippy.hx` and is written in haXe, which compiles directly to SWF. You can customize Clippy via that source code.

**Comment by ionull** [comment]
thank you very much!

-- Sent from my Palm Pre
On 12 Apr 2011 23:41,
reply@reply.github.com
wrote:
The source is in `clippy.hx` and is written in haXe, which compiles
directly to SWF. You can customize Clippy via that source code.

## 

Reply to this email directly or view it on GitHub:
https://github.com/mojombo/clippy/issues/13#comment_990243
