### ISSUE TITLE
If the text to copy contains & ...

### ISSUE THREAD

**Issue by kedarmhaswade** [mojombo/clippy#25]
the remaining text is ignored :( This is a weird issue.

If I used: <span><%= clippy("https://foo.com/abc?status=true&id=1234") %></span>

the text that actually goes to clipboard is "https://foo.com/abc?status=true" i.e. the first '&' and remaining text is stripped off.

Anybody?

**Comment by hulvei3** [comment]
I also need a solution on this

Any progress on this issue, or workarounds..

UPDATE: sorry - workaround found here https://github.com/mojombo/clippy/issues/1 :)

**Comment by kedarmhaswade** [comment]
URLencoing works.
