### ISSUE TITLE
Clippy cannot copy + signs

### ISSUE THREAD

**Issue by lpgauth** [mojombo/clippy#4]
It seems that Clippy is unable to copy + signs.

To reproduce, using the rails helper, use the code bellow:
<%=h clippy("+++").html_safe %>

**Comment by lpgauth** [comment]
<%=h clippy(CGI.escape("+++")) %> works.

**Comment by ericabouaf** [comment]
Same thing for '&' 
Maybe put in the README that if it is used for a URL, you need to encode it

**Comment by annie-l** [comment]
You can also replace the + in JS to encode it:

<code>myString.replace("+", "%2B");</code>
